version: '3.8'

services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env  

  prisma:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: generate
    depends_on:
      - mongodb
